var controller = new ScrollMagic.Controller();

$(function () {

  //Pin number tags
  var num1_scene = new ScrollMagic.Scene({triggerElement: "#hardware_data", triggerHook: 0, duration: "50%"})
  .setPin("#hardware_data_info_text")
  .addTo(controller)
  var num2_scene = new ScrollMagic.Scene({triggerElement: "#battery_chamber_data", triggerHook: 0, duration: "50%"})
  .setPin("#battery_chamber_data_info_text")
  .addTo(controller)
  var num3_scene = new ScrollMagic.Scene({triggerElement: "#battery_data", triggerHook: 0, duration: "50%"})
  .setPin("#battery_data_info_text")
  .addTo(controller)
  var num4_scene = new ScrollMagic.Scene({triggerElement: "#camera_mount_data", triggerHook: 0, duration: "50%"})
  .setPin("#camera_mount_data_info_text")
  .addTo(controller)
  var num5_scene = new ScrollMagic.Scene({triggerElement: "#main_plate_data", triggerHook: 0, duration: "50%"})
  .setPin("#main_plate_data_info_text")
  .addTo(controller)
  var num5_scene = new ScrollMagic.Scene({triggerElement: "#bottom_chamber_data", triggerHook: 0, duration: "50%"})
  .setPin("#bottom_chamber_info_text")
  .addTo(controller)

  //Part number Opacity in
  var animationDuration = {duration: 400, ease: "easeInSine"}
  var num1_scene_2 = new ScrollMagic.Scene({triggerElement: "#hardware_data", triggerHook: 0.1})
  .setVelocity("#hardware_data_info_text", {opacity: 1}, animationDuration)
  .addTo(controller)
  var num2_scene_2 = new ScrollMagic.Scene({triggerElement: "#battery_chamber_data", triggerHook: 0.1})
  .setVelocity("#battery_chamber_data_info_text", {opacity: 1}, animationDuration)
  .addTo(controller)
  var num3_scene_2 = new ScrollMagic.Scene({triggerElement: "#battery_data", triggerHook: 0.1})
  .setVelocity("#battery_data_info_text", {opacity: 1}, animationDuration)
  .addTo(controller)
  var num4_scene_2 = new ScrollMagic.Scene({triggerElement: "#camera_mount_data", triggerHook: 0.1})
  .setVelocity("#camera_mount_data_info_text", {opacity: 1}, animationDuration)
  .addTo(controller)
  var num5_scene_2 = new ScrollMagic.Scene({triggerElement: "#main_plate_data", triggerHook: 0.1})
  .setVelocity("#main_plate_data_info_text", {opacity: 1}, animationDuration)
  .addTo(controller)
  var num6_scene_2 = new ScrollMagic.Scene({triggerElement: "#bottom_chamber_data", triggerHook: 0.1})
  .setVelocity("#bottom_chamber_info_text", {opacity: 1}, animationDuration)
  .addTo(controller)

  //Part number Opacity out
  var num1_scene_2 = new ScrollMagic.Scene({triggerElement: "#battery_chamber_data", triggerHook: 0.5})
  .setVelocity("#hardware_data_info_text", {opacity: 0}, animationDuration)
  .addTo(controller)
  var num2_scene_2 = new ScrollMagic.Scene({triggerElement: "#battery_data", triggerHook: 0.5})
  .setVelocity("#battery_chamber_data_info_text", {opacity: 0}, animationDuration)
  .addTo(controller)
  var num3_scene_2 = new ScrollMagic.Scene({triggerElement: "#camera_mount_data", triggerHook: 0.5})
  .setVelocity("#battery_data_info_text", {opacity: 0}, animationDuration)
  .addTo(controller)
  var num4_scene_2 = new ScrollMagic.Scene({triggerElement: "#main_plate_data", triggerHook: 0.5})
  .setVelocity("#camera_mount_data_info_text", {opacity: 0}, animationDuration)
  .addTo(controller)
  var num5_scene_2 = new ScrollMagic.Scene({triggerElement: "#bottom_chamber_data", triggerHook: 0.5})
  .setVelocity("#main_plate_data_info_text", {opacity: 0}, animationDuration)
  .addTo(controller)
  var num6_scene_2 = new ScrollMagic.Scene({triggerElement: "#end", triggerHook: 0.5})
  .setVelocity("#bottom_chamber_info_text", {opacity: 0}, animationDuration)
  .addTo(controller)
})
