var controller = new ScrollMagic.Controller();

$(function () {

  //SVG lines
  function pathPrepare ($el) {
      var lineLength = $el[0].getTotalLength();
      $el.css("stroke-dasharray", lineLength);
      $el.css("stroke-dashoffset", lineLength);
  }

  var $hardware_line_top = $("#hardware_line_top path")
  var $hardware_line_bottom = $("#hardware_line_bottom path")
  var $battery_chamber_line_top = $("#battery_chamber_line_top path")
  var $battery_chamber_line_bottom = $("#battery_chamber_line_bottom path")
  var $battery_line_top = $("#battery_line_top path")
  var $battery_line_bottom = $("#battery_line_bottom path")
  var $camera_mount_line_top = $("#camera_mount_line_top path")
  var $camera_mount_line_bottom = $("#camera_mount_line_bottom path")
  var $main_plate_line_top = $("#main_plate_line_top path")
  var $main_plate_line_bottom = $("#main_plate_line_bottom path")
  var $bottom_chamber_line_top = $("#bottom_chamber_line_top path")
  var $bottom_chamber_line_bottom = $("#bottom_chamber_line_bottom path")
  // prepare SVG
 pathPrepare($hardware_line_top)
 pathPrepare($hardware_line_bottom)
 pathPrepare($battery_chamber_line_top)
 pathPrepare($battery_chamber_line_bottom)
 pathPrepare($battery_line_top)
 pathPrepare($battery_line_bottom)
 pathPrepare($camera_mount_line_top)
 pathPrepare($camera_mount_line_bottom)
 pathPrepare($main_plate_line_top)
 pathPrepare($main_plate_line_bottom)
 pathPrepare($bottom_chamber_line_top)
 pathPrepare($bottom_chamber_line_bottom)

  // build tween
  var tween_hardware_line_top = new TimelineMax()
  .add(TweenMax.to($hardware_line_top, 1, {strokeDashoffset: 0, ease:Linear.easeNone}))
  var tween_hardware_line_bottom = new TimelineMax()
  .add(TweenMax.to($hardware_line_bottom, 1, {strokeDashoffset: 0, ease:Linear.easeNone}))
  var tween_battery_chamber_line_top = new TimelineMax()
  .add(TweenMax.to($battery_chamber_line_top, 1, {strokeDashoffset: 0, ease:Linear.easeNone}))
  var tween_battery_chamber_line_bottom = new TimelineMax()
  .add(TweenMax.to($battery_chamber_line_bottom, 1, {strokeDashoffset: 0, ease:Linear.easeNone}))
  var tween_battery_line_top = new TimelineMax()
  .add(TweenMax.to($battery_line_top, 1, {strokeDashoffset: 0, ease:Linear.easeNone}))
  var tween_battery_line_bottom = new TimelineMax()
  .add(TweenMax.to($battery_line_bottom, 1, {strokeDashoffset: 0, ease:Linear.easeNone}))
  var tween_camera_mount_line_top = new TimelineMax()
  .add(TweenMax.to($camera_mount_line_top, 1, {strokeDashoffset: 0, ease:Linear.easeNone}))
  var tween_camera_mount_line_bottom = new TimelineMax()
  .add(TweenMax.to($camera_mount_line_bottom, 1, {strokeDashoffset: 0, ease:Linear.easeNone}))
  var tween_main_plate_line_top = new TimelineMax()
  .add(TweenMax.to($main_plate_line_top, 1, {strokeDashoffset: 0, ease:Linear.easeNone}))
  var tween_main_plate_line_bottom = new TimelineMax()
  .add(TweenMax.to($main_plate_line_bottom, 1, {strokeDashoffset: 0, ease:Linear.easeNone}))
  var tween_bottom_chamber_line_top = new TimelineMax()
  .add(TweenMax.to($bottom_chamber_line_top, 1, {strokeDashoffset: 0, ease:Linear.easeNone}))
  var tween_bottom_chamber_line_bottom = new TimelineMax()
  .add(TweenMax.to($bottom_chamber_line_bottom, 1, {strokeDashoffset: 0, ease:Linear.easeNone}))

  //Animate svg paths
  var hardware_line_top_scene = new ScrollMagic.Scene({triggerElement: "#hardware_data", duration: "25%", triggerHook: 0.1, tweenChanges: true})
  .setTween(tween_hardware_line_top)
  .addTo(controller)
  var hardware_line_bottom_scene = new ScrollMagic.Scene({triggerElement: "#hardware_data", duration: "25%", triggerHook: 0.1, tweenChanges: true})
  .setTween(tween_hardware_line_bottom)
  .addTo(controller)
  var battery_chamber_line_top_scene = new ScrollMagic.Scene({triggerElement: "#battery_chamber_data", duration: "25%", triggerHook: 0.1, tweenChanges: true})
  .setTween(tween_battery_chamber_line_top)
  .addTo(controller)
  var battery_chamber_line_bottom_scene = new ScrollMagic.Scene({triggerElement: "#battery_chamber_data", duration: "25%", triggerHook: 0.1, tweenChanges: true})
  .setTween(tween_battery_chamber_line_bottom)
  .addTo(controller)
  var battery_line_top_scene = new ScrollMagic.Scene({triggerElement: "#battery_data", duration: "25%", triggerHook: 0.1, tweenChanges: true})
  .setTween(tween_battery_line_top)
  .addTo(controller)
  var battery_line_bottom_scene = new ScrollMagic.Scene({triggerElement: "#battery_data", duration: "25%", triggerHook: 0.1, tweenChanges: true})
  .setTween(tween_battery_line_bottom)
  .addTo(controller)
  var camera_mount_line_top_scene = new ScrollMagic.Scene({triggerElement: "#camera_mount_data", duration: "25%", triggerHook: 0.1, tweenChanges: true})
  .setTween(tween_camera_mount_line_top)
  .addTo(controller)
  var camera_mount_line_bottom_scene = new ScrollMagic.Scene({triggerElement: "#camera_mount_data", duration: "25%", triggerHook: 0.1, tweenChanges: true})
  .setTween(tween_camera_mount_line_bottom)
  .addTo(controller)
  var main_plate_line_top_scene = new ScrollMagic.Scene({triggerElement: "#main_plate_data", duration: "25%", triggerHook: 0.1, tweenChanges: true})
  .setTween(tween_main_plate_line_top)
  .addTo(controller)
  var main_plate_line_bottom_scene = new ScrollMagic.Scene({triggerElement: "#main_plate_data", duration: "25%", triggerHook: 0.1, tweenChanges: true})
  .setTween(tween_main_plate_line_bottom)
  .addTo(controller)
  var bottom_chamber_line_top_scene = new ScrollMagic.Scene({triggerElement: "#bottom_chamber_data", duration: "25%", triggerHook: 0.1, tweenChanges: true})
  .setTween(tween_bottom_chamber_line_top)
  .addTo(controller)
  var bottom_chamber_line_bottom_scene = new ScrollMagic.Scene({triggerElement: "#bottom_chamber_data", duration: "25%", triggerHook: 0.1, tweenChanges: true})
  .setTween(tween_bottom_chamber_line_bottom)
  .addTo(controller)

  //Pin svg paths
  var hardware_line_top_scene = new ScrollMagic.Scene({triggerElement: "#hardware_data", triggerHook: 0, duration: "50%"})
  .setPin("#hardware_line_top")
  .addTo(controller)
  var hardware_line_bottom_scene = new ScrollMagic.Scene({triggerElement: "#hardware_data", triggerHook: 0, duration: "50%"})
  .setPin("#hardware_line_bottom")
  .addTo(controller)
  var battery_chamber_line_top_scene = new ScrollMagic.Scene({triggerElement: "#battery_chamber_data", triggerHook: 0, duration: "50%"})
  .setPin("#battery_chamber_line_top")
  .addTo(controller)
  var battery_chamber_line_bottom_scene = new ScrollMagic.Scene({triggerElement: "#battery_chamber_data", triggerHook: 0, duration: "50%"})
  .setPin("#battery_chamber_line_bottom")
  .addTo(controller)
  var battery_line_top_scene = new ScrollMagic.Scene({triggerElement: "#battery_data", triggerHook: 0, duration: "50%"})
  .setPin("#battery_line_top")
  .addTo(controller)
  var battery_line_bottom_scene = new ScrollMagic.Scene({triggerElement: "#battery_data", triggerHook: 0, duration: "50%"})
  .setPin("#battery_line_bottom")
  .addTo(controller)
  var camera_mount_line_top_scene = new ScrollMagic.Scene({triggerElement: "#camera_mount_data", triggerHook: 0, duration: "50%"})
  .setPin("#camera_mount_line_top")
  .addTo(controller)
  var camera_mount_line_bottom_scene = new ScrollMagic.Scene({triggerElement: "#camera_mount_data", triggerHook: 0, duration: "50%"})
  .setPin("#camera_mount_line_bottom")
  .addTo(controller)
  var main_plate_line_top_scene = new ScrollMagic.Scene({triggerElement: "#main_plate_data", triggerHook: 0, duration: "50%"})
  .setPin("#main_plate_line_top")
  .addTo(controller)
  var main_plate_line_bottom_scene = new ScrollMagic.Scene({triggerElement: "#main_plate_data", triggerHook: 0, duration: "50%"})
  .setPin("#main_plate_line_bottom")
  .addTo(controller)

  //Remove svg paths
  var hardware_line_top_scene = new ScrollMagic.Scene({triggerElement: "#battery_chamber_data", triggerHook: 0.5})
  .setVelocity("#hardware_line_top", {opacity: 0}, "easeInSine")
  .addTo(controller)
  var hardware_line_bottom_scene = new ScrollMagic.Scene({triggerElement: "#battery_chamber_data", triggerHook: 0.5})
  .setVelocity("#hardware_line_bottom", {opacity: 0}, "easeInSine")
  .addTo(controller)
  var battery_chamber_line_top_scene = new ScrollMagic.Scene({triggerElement: "#battery_data", triggerHook: 0.5})
  .setVelocity("#battery_chamber_line_top", {opacity: 0}, "easeInSine")
  .addTo(controller)
  var battery_chamber_line_bottom_scene = new ScrollMagic.Scene({triggerElement: "#battery_data", triggerHook: 0.5})
  .setVelocity("#battery_chamber_line_bottom", {opacity: 0}, "easeInSine")
  .addTo(controller)
  var battery_line_top_scene = new ScrollMagic.Scene({triggerElement: "#camera_mount_data", triggerHook: 0.5})
  .setVelocity("#battery_line_top", {opacity: 0}, "easeInSine")
  .addTo(controller)
  var battery_line_bottom_scene = new ScrollMagic.Scene({triggerElement: "#camera_mount_data", triggerHook: 0.5})
  .setVelocity("#battery_line_bottom", {opacity: 0}, "easeInSine")
  .addTo(controller)
  var camera_mount_line_top_scene = new ScrollMagic.Scene({triggerElement: "#main_plate_data", triggerHook: 0.5})
  .setVelocity("#camera_mount_line_top", {opacity: 0}, "easeInSine")
  .addTo(controller)
  var camera_mount_line_bottom_scene = new ScrollMagic.Scene({triggerElement: "#main_plate_data", triggerHook: 0.5})
  .setVelocity("#camera_mount_line_bottom", {opacity: 0}, "easeInSine")
  .addTo(controller)
  var main_plate_line_top_scene = new ScrollMagic.Scene({triggerElement: "#bottom_chamber_data", triggerHook: 0.5})
  .setVelocity("#main_plate_line_top", {opacity: 0}, "easeInSine")
  .addTo(controller)
  var main_plate_line_bottom_scene = new ScrollMagic.Scene({triggerElement: "#bottom_chamber_data", triggerHook: 0.5})
  .setVelocity("#main_plate_line_bottom", {opacity: 0}, "easeInSine")
  .addTo(controller)
  var main_plate_line_top_scene = new ScrollMagic.Scene({triggerElement: "#awards", triggerHook: 0.5})
  .setVelocity("#bottom_chamber_line_top", {opacity: 0}, "easeInSine")
  .addTo(controller)
  var main_plate_line_bottom_scene = new ScrollMagic.Scene({triggerElement: "#awards", triggerHook: 0.5})
  .setVelocity("#bottom_chamber_line_bottom", {opacity: 0}, "easeInSine")
  .addTo(controller)
})
