var controller = new ScrollMagic.Controller()

$(function () {

  // Pin drone in place
  var triggerElement = {triggerElement: "#moto", triggerHook: 0, duration: "750%"}

  var top_screws = new ScrollMagic.Scene(triggerElement)
  .setPin("#top_screws")
  .addTo(controller)
  var top_plate = new ScrollMagic.Scene(triggerElement)
  .setPin("#top_plate")
  .addTo(controller)
  var front_polls = new ScrollMagic.Scene(triggerElement)
  .setPin("#front_polls")
  .addTo(controller)
  var camera_holder = new ScrollMagic.Scene(triggerElement)
  .setPin("#camera_holder")
  .addTo(controller)
  var camera = new ScrollMagic.Scene(triggerElement)
  .setPin("#camera")
  .addTo(controller)
  var battery_plastic = new ScrollMagic.Scene(triggerElement)
  .setPin("#battery_plastic")
  .addTo(controller)
  var battey_plate = new ScrollMagic.Scene(triggerElement)
  .setPin("#battey_plate")
  .addTo(controller)
  var battery = new ScrollMagic.Scene(triggerElement)
  .setPin("#battery")
  .addTo(controller)
  var back_polls = new ScrollMagic.Scene(triggerElement)
  .setPin("#back_polls")
  .addTo(controller)
  var motors = new ScrollMagic.Scene(triggerElement)
  .setPin("#motors")
  .addTo(controller)
  var main_plate = new ScrollMagic.Scene(triggerElement)
  .setPin("#main_plate")
  .addTo(controller)
  var antenna = new ScrollMagic.Scene(triggerElement)
  .setPin("#antenna")
  .addTo(controller)
  var bottom_plastic = new ScrollMagic.Scene(triggerElement)
  .setPin("#bottom_plastic")
  .addTo(controller)
  var electronics = new ScrollMagic.Scene(triggerElement)
  .setPin("#electronics")
  .addTo(controller)
  var down_plate = new ScrollMagic.Scene(triggerElement)
  .setPin("#down_plate")
  .addTo(controller)
  var bottom_screws = new ScrollMagic.Scene(triggerElement)
  .setPin("#bottom_screws")
  .addTo(controller)
})
