var controller = new ScrollMagic.Controller()

$(function () {

  // Bottom Chamber scene
  var triggerElement = {triggerElement: "#end", triggerHook: 0.7}
  var animationDuration = {duration: "fast", ease: "easeInSine"}

  var bottom_chamber1 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#top_screws", {opacity: 0.3}, animationDuration)
  .addTo(controller)
  var bottom_chamber2 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#top_plate", {opacity: 0.3}, animationDuration)
  .addTo(controller)
  var bottom_chamber3 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#front_polls", {opacity: 0.3}, animationDuration)
  .addTo(controller)
  var bottom_chamber4 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#camera_holder", {opacity: 0.3}, animationDuration)
  .addTo(controller)
  var bottom_chamber5 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#camera", {opacity: 0.3}, animationDuration)
  .addTo(controller)
  var bottom_chamber6 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#battery_plastic", {opacity: 0.3}, animationDuration)
  .addTo(controller)
  var bottom_chamber7 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#battery_plate", {opacity: 0.3}, animationDuration)
  .addTo(controller)
  var bottom_chamber8 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#battery", {opacity: 0.3}, animationDuration)
  .addTo(controller)
  var bottom_chamber9 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#back_polls", {opacity: 0.3}, animationDuration)
  .addTo(controller)
  var bottom_chamber10 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#motors", {opacity: 0.3}, animationDuration)
  .addTo(controller)
  var bottom_chamber11 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#main_plate", {opacity: 0.3}, animationDuration)
  .addTo(controller)
  var bottom_chamber12 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#antenna", {opacity: 1}, animationDuration)
  .addTo(controller)
  var bottom_chamber13 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#bottom_plastic", {opacity: 1}, animationDuration)
  .addTo(controller)
  var bottom_chamber14 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#electronics", {opacity: 1}, animationDuration)
  .addTo(controller)
  var bottom_chamber15 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#down_plate", {opacity: 1}, animationDuration)
  .addTo(controller)
  var bottom_chamber16 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#bottom_screws", {opacity: 0.3}, animationDuration)
  .addTo(controller)
})
