var controller = new ScrollMagic.Controller()

$(function () {

 // Battery scene
 var triggerElement = {triggerElement: "#camera_mount_data", triggerHook: 0.7}
 var animationDuration = {duration: "fast", ease: "easeInSine"}

 var battery1 = new ScrollMagic.Scene(triggerElement)
 .setVelocity("#top_screws", {opacity: 0.3}, animationDuration)
 .addTo(controller)
 var battery2 = new ScrollMagic.Scene(triggerElement)
 .setVelocity("#top_plate", {opacity: 0.3}, animationDuration)
 .addTo(controller)
 var battery3 = new ScrollMagic.Scene(triggerElement)
 .setVelocity("#front_polls", {opacity: 0.3}, animationDuration)
 .addTo(controller)
 var battery4 = new ScrollMagic.Scene(triggerElement)
 .setVelocity("#camera_holder", {opacity: 0.3}, animationDuration)
 .addTo(controller)
 var battery5 = new ScrollMagic.Scene(triggerElement)
 .setVelocity("#camera", {opacity: 0.3}, animationDuration)
 .addTo(controller)
 var battery6 = new ScrollMagic.Scene(triggerElement)
 .setVelocity("#battery_plastic", {opacity: 0.3}, animationDuration)
 .addTo(controller)
 var battery7 = new ScrollMagic.Scene(triggerElement)
 .setVelocity("#battey_plate", {opacity: 0.3}, animationDuration)
 .addTo(controller)
 var battery8 = new ScrollMagic.Scene(triggerElement)
 .setVelocity("#battery", {opacity: 1}, animationDuration)
 .addTo(controller)
 var battery9 = new ScrollMagic.Scene(triggerElement)
 .setVelocity("#back_polls", {opacity: 0.3}, animationDuration)
 .addTo(controller)
 var battery10 = new ScrollMagic.Scene(triggerElement)
 .setVelocity("#motors", {opacity: 0.3}, animationDuration)
 .addTo(controller)
 var battery11 = new ScrollMagic.Scene(triggerElement)
 .setVelocity("#main_plate", {opacity: 0.3}, animationDuration)
 .addTo(controller)
 var battery12 = new ScrollMagic.Scene(triggerElement)
 .setVelocity("#antenna", {opacity: 0.3}, animationDuration)
 .addTo(controller)
 var battery13 = new ScrollMagic.Scene(triggerElement)
 .setVelocity("#bottom_plastic", {opacity: 0.3}, animationDuration)
 .addTo(controller)
 var battery14 = new ScrollMagic.Scene(triggerElement)
 .setVelocity("#electronics", {opacity: 0.3}, animationDuration)
 .addTo(controller)
 var battery15 = new ScrollMagic.Scene(triggerElement)
 .setVelocity("#down_plate", {opacity: 0.3}, animationDuration)
 .addTo(controller)
 var battery16 = new ScrollMagic.Scene(triggerElement)
 .setVelocity("#bottom_screws", {opacity: 0.3}, animationDuration)
 .addTo(controller)

})
