var controller = new ScrollMagic.Controller()

$(function () {

  // Camera Mount scene
  var triggerElement = {triggerElement: "#main_plate_data", triggerHook: 0.7}
  var animationDuration = {duration: "fast", ease: "easeInSine"}

  var camera_mount1 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#top_screws", {opacity: 0.3}, animationDuration)
  .addTo(controller)
  var camera_mount2 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#top_plate", {opacity: 0.3}, animationDuration)
  .addTo(controller)
  var camera_mount3 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#front_polls", {opacity: 0.3}, animationDuration)
  .addTo(controller)
  var camera_mount4 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#camera_holder", {opacity: 1}, animationDuration)
  .addTo(controller)
  var camera_mount5 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#camera", {opacity: 1}, animationDuration)
  .addTo(controller)
  var camera_mount6 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#battery_plastic", {opacity: 0.3}, animationDuration)
  .addTo(controller)
  var camera_mount7 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#battery_plate", {opacity: 0.3}, animationDuration)
  .addTo(controller)
  var camera_mount8 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#battery", {opacity: 0.3}, animationDuration)
  .addTo(controller)
  var camera_mount9 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#back_polls", {opacity: 0.3}, animationDuration)
  .addTo(controller)
  var camera_mount10 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#motors", {opacity: 0.3}, animationDuration)
  .addTo(controller)
  var camera_mount11 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#main_plate", {opacity: 0.3}, animationDuration)
  .addTo(controller)
  var camera_mount12 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#antenna", {opacity: 0.3}, animationDuration)
  .addTo(controller)
  var camera_mount13 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#bottom_plastic", {opacity: 0.3}, animationDuration)
  .addTo(controller)
  var camera_mount14 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#electronics", {opacity: 0.3}, animationDuration)
  .addTo(controller)
  var camera_mount15 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#down_plate", {opacity: 0.3}, animationDuration)
  .addTo(controller)
  var camera_mount16 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#bottom_screws", {opacity: 0.3}, animationDuration)
  .addTo(controller)
})
