var controller = new ScrollMagic.Controller()

$(function () {

  // Battery Chamber scene
  var animationDuration = {duration: "fast", ease: "easeInSine"}
  var triggerElement = {triggerElement: "#battery_data", triggerHook: 0.7}

  var battery_chamber1 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#top_screws", {opacity: 0.3}, animationDuration)
  .addTo(controller)
  var battery_chamber2 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#top_plate", {opacity: 1}, animationDuration)
  .addTo(controller)
  var battery_chamber3 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#front_polls", {opacity: 1}, animationDuration)
  .addTo(controller)
  var battery_chamber4 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#camera_holder", {opacity: 0.3}, animationDuration)
  .addTo(controller)
  var battery_chamber5 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#camera", {opacity: 0.3}, animationDuration)
  .addTo(controller)
  var battery_chamber6 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#battery_plastic", {opacity: 1}, animationDuration)
  .addTo(controller)
  var battery_chamber7 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#battey_plate", {opacity: 1}, animationDuration)
  .addTo(controller)
  var battery_chamber8 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#battery", {opacity: 0.3}, animationDuration)
  .addTo(controller)
  var battery_chamber9 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#back_polls", {opacity: 1}, animationDuration)
  .addTo(controller)
  var battery_chamber10 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#motors", {opacity: 0.3}, animationDuration)
  .addTo(controller)
  var battery_chamber11 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#main_plate", {opacity: 1}, animationDuration)
  .addTo(controller)
  var battery_chamber12 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#antenna", {opacity: 0.3}, animationDuration)
  .addTo(controller)
  var battery_chamber13 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#bottom_plastic", {opacity: 0.3}, animationDuration)
  .addTo(controller)
  var battery_chamber14 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#electronics", {opacity: 0.3}, animationDuration)
  .addTo(controller)
  var battery_chamber15 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#down_plate", {opacity: 0.3}, animationDuration)
  .addTo(controller)
  var battery_chamber16 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#bottom_screws", {opacity: 0.3}, animationDuration)
  .addTo(controller)
})
