var controller = new ScrollMagic.Controller()

$(function () {

  // Hardware scene
  var animationDuration = {duration: "fast", ease: "easeInSine"}
  var triggerElement = {triggerElement: "#battery_chamber_data", triggerHook: 0.7}

  var hardware1 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#top_screws", {opacity: 1}, animationDuration)
  .addTo(controller)
  var hardware2 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#top_plate", {opacity: 0.3}, animationDuration)
  .addTo(controller)
  var hardware3 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#front_polls", {opacity: 1}, animationDuration)
  .addTo(controller)
  var hardware4 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#camera_holder", {opacity: 0.3}, animationDuration)
  .addTo(controller)
  var hardware5 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#camera", {opacity: 0.3}, animationDuration)
  .addTo(controller)
  var hardware6 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#battery_plastic", {opacity: 0.3}, animationDuration)
  .addTo(controller)
  var hardware7 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#battey_plate", {opacity: 0.3}, animationDuration)
  .addTo(controller)
  var hardware8 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#battery", {opacity: 0.3}, animationDuration)
  .addTo(controller)
  var hardware9 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#back_polls", {opacity: 1}, animationDuration)
  .addTo(controller)
  var hardware10 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#motors", {opacity: 0.3}, animationDuration)
  .addTo(controller)
  var hardware11 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#main_plate", {opacity: 0.3}, animationDuration)
  .addTo(controller)
  var hardware12 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#antenna", {opacity: 0.3}, animationDuration)
  .addTo(controller)
  var hardware13 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#bottom_plastic", {opacity: 0.3}, animationDuration)
  .addTo(controller)
  var hardware14 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#electronics", {opacity: 0.3}, animationDuration)
  .addTo(controller)
  var hardware15 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#down_plate", {opacity: 0.3}, animationDuration)
  .addTo(controller)
  var hardware16 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#bottom_screws", {opacity: 1}, animationDuration)
  .addTo(controller)
})
