var controller = new ScrollMagic.Controller()

$(function () {

  // Main Plate scene
  var triggerElement = {triggerElement: "#bottom_chamber_data", triggerHook: 0.7}
  var animationDuration = {duration: "fast", ease: "easeInSine"}

  var main_plate1 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#top_screws", {opacity: 0.3}, animationDuration)
  .addTo(controller)
  var main_plate2 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#top_plate", {opacity: 0.3}, animationDuration)
  .addTo(controller)
  var main_plate3 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#front_polls", {opacity: 0.3}, animationDuration)
  .addTo(controller)
  var main_plate4 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#camera_holder", {opacity: 0.3}, animationDuration)
  .addTo(controller)
  var main_plate5 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#camera", {opacity: 0.3}, animationDuration)
  .addTo(controller)
  var main_plate6 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#battery_plastic", {opacity: 0.3}, animationDuration)
  .addTo(controller)
  var main_plate7 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#battery_plate", {opacity: 0.3}, animationDuration)
  .addTo(controller)
  var main_plate8 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#battery", {opacity: 0.3}, animationDuration)
  .addTo(controller)
  var main_plate9 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#back_polls", {opacity: 0.3}, animationDuration)
  .addTo(controller)
  var main_plate10 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#motors", {opacity: 0.3}, animationDuration)
  .addTo(controller)
  var main_plate11 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#main_plate", {opacity: 1}, animationDuration)
  .addTo(controller)
  var main_plate12 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#antenna", {opacity: 0.3}, animationDuration)
  .addTo(controller)
  var main_plate13 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#bottom_plastic", {opacity: 0.3}, animationDuration)
  .addTo(controller)
  var main_plate14 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#electronics", {opacity: 0.3}, animationDuration)
  .addTo(controller)
  var main_plate15 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#down_plate", {opacity: 0.3}, animationDuration)
  .addTo(controller)
  var main_plate16 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#bottom_screws", {opacity: 0.3}, animationDuration)
  .addTo(controller)

})
