var controller = new ScrollMagic.Controller()

$(function () {

 // Move drone to side and minimize
  var animation = {translateX: "20vw", width: "65vw", translateY: "2vh"}
  var animationDuration = { duration: 1500, ease: "easeInSine"}
  var triggerElement = {triggerElement: "#hardware_data", triggerHook: 0.8}

  var start1 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#top_screws", animation, animationDuration)
  .addTo(controller)
  var start2 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#top_plate", animation, animationDuration)
  .addTo(controller)
  var start3 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#front_polls", animation, animationDuration)
  .addTo(controller)
  var start4 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#camera_holder", animation, animationDuration)
  .addTo(controller)
  var start5 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#camera", animation, animationDuration)
  .addTo(controller)
  var start6 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#battery_plastic", animation, animationDuration)
  .addTo(controller)
  var start7 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#battey_plate", animation, animationDuration)
  .addTo(controller)
  var start8 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#battery", animation, animationDuration)
  .addTo(controller)
  var start9 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#back_polls", animation, animationDuration)
  .addTo(controller)
  var start10 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#motors", animation, animationDuration)
  .addTo(controller)
  var start11 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#main_plate", animation, animationDuration)
  .addTo(controller)
  var start12 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#antenna", animation, animationDuration)
  .addTo(controller)
  var start13 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#bottom_plastic", animation, animationDuration)
  .addTo(controller)
  var start14 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#electronics", animation, animationDuration)
  .addTo(controller)
  var start15 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#down_plate", animation, animationDuration)
  .addTo(controller)
  var start16 = new ScrollMagic.Scene(triggerElement)
  .setVelocity("#bottom_screws", animation, animationDuration)
  .addTo(controller)
})
